version: '3.8'

services:
  api:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: api
    image: service-rest-api
    restart: on-failure
    env_file: .env
    ports:
      - ${PORT}:${PORT}